fixtures:
  forge_modules:
    augeas_file: 'camptocamp-augeas_file'
    augeasproviders_core: 'herculesteam-augeasproviders_core'
    augeasproviders_shellvar: 'herculesteam-augeasproviders_shellvar'
    stdlib: 'puppetlabs-stdlib'
    systemd: 'camptocamp-systemd'
  symlinks:
    varnish: "#{source_dir}"
